### ISSUE TITLE
Several Common Issues

### ISSUE THREAD

**Issue by HarunRRayhan** [raselupm/website-manager#2]
Bhai,
I take a look at the source code. I'll do a pull request when getting time to go over it fully. But here are some issues I found: 

1. You are using `env()` function in lots of places in your code. When you run `php artisan config:cache` (which you should do in the production server for performance), it will return `null`. You should on add `env()` inside `config/` folder only. And then use `config('app.my-key')` in the code for the value. Read about it here 👉 https://laravel.com/docs/master/helpers#method-env
2. Use `Http::head()` instead of `Http::get()` in `App\Jobs\CreateEvent`'s `handle` method (if anywhere else you used). You are not doing anything with the content/body of the domain, it's a huge loss of the resource.  
3. You are pinging all of the domain in one single job, that's not a good idea. Suppose, I have 1,000 domains. I can never check all of them in one job, it will fail for sure. If it's me, I'll create a command to push all of the domains in separate queues, one in each. Then run then command by the schedule for example in every five minutes. This way job will be lightweight and the failure rate will be lower. 
4. You are sending Twilio SMS notification from `CreateEvent` job. Try to send Twilio notification in the notification and separate it from the job. Like you are doing for `SlackMonitor`. 

These things will give a huge performance boost.

**Comment by raselupm** [comment]
Thank you so much. I will closely look at these. Really very helpful.
